'use strict';
const CFG={base:'https://resultados.tse.jus.br/oficial/ele2026/6257/dados',ele:'006257',cargo:'0001',mainMs:15000,ufMs:60000,ufs:['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO']};
const UF={AC:'Acre',AL:'Alagoas',AP:'Amapá',AM:'Amazonas',BA:'Bahia',CE:'Ceará',DF:'Distrito Federal',ES:'Espírito Santo',GO:'Goiás',MA:'Maranhão',MT:'Mato Grosso',MS:'Mato Grosso do Sul',MG:'Minas Gerais',PA:'Pará',PB:'Paraíba',PR:'Paraná',PE:'Pernambuco',PI:'Piauí',RJ:'Rio de Janeiro',RN:'Rio Grande do Norte',RS:'Rio Grande do Sul',RO:'Rondônia',RR:'Roraima',SC:'Santa Catarina',SP:'São Paulo',SE:'Sergipe',TO:'Tocantins'};
const $=id=>document.getElementById(id),fi=new Intl.NumberFormat('pt-BR'),fp=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
let data=null,cands=[],sel=null,busy=false;
const num=(v,d=0)=>{if(v==null||v==='')return d;if(typeof v==='number')return Number.isFinite(v)?v:d;let s=String(v).trim();if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:d};
const pct=v=>Math.max(0,Math.min(100,num(v)));
const url=scope=>{const u=scope.toLowerCase(),f=scope==='BR'?`br-c${CFG.cargo}-e${CFG.ele}-u.json`:`${u}-c${CFG.cargo}-e${CFG.ele}-u.json`;return `${CFG.base}/${u}/${f}`};
function candidates(j){const a=[];for(const c of j?.carg||[])for(const g of c?.agr||[])for(const p of g?.par||[])for(const x of p?.cand||[])a.push({...x,party:p.sg||'',group:g.nm||'',dest:x.dvt||p.dvt||''});return a}
function validDest(c){const d=String(c?.dest||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return !d||d.startsWith('valido')}
async function load(u,key,ms=8500){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),ms);try{const r=await fetch(`${u}?t=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/json'},signal:ctl.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);const j=await r.json();try{localStorage.setItem(key,JSON.stringify(j))}catch{}return{j,stale:false}}catch(e){try{const x=localStorage.getItem(key);if(x)return{j:JSON.parse(x),stale:true}}catch{}throw e}finally{clearTimeout(t)}}
function met(j,c){const vv=num(j?.v?.vv),cv=num(c?.vap),share=vv?100*cv/vv:0,te=num(j?.e?.te),est=num(j?.e?.est),rem=Math.max(0,num(j?.e?.esnt,Math.max(0,te-est))),max=vv+rem,needMax=Math.floor(max/2)+1,needNow=Math.floor(vv/2)+1;return{vv,cv,share,rem,worst:Math.max(0,needMax-cv),guaranteed:cv>=needMax,impossible:cv+rem<needMax,delta:cv-needNow}}
function source(kind,text){const p=$('sourcePill');p.classList.remove('live','error');if(kind)p.classList.add(kind);$('sourceStatus').textContent=text}
function notice(kind,text){const n=$('notice');n.className=`notice ${kind}`;n.textContent=text}
function fillSelect(){const s=$('candidateSelect'),prev=sel?.sqcand&&String(sel.sqcand);s.innerHTML='';const sorted=[...cands].sort((a,b)=>num(a.n)-num(b.n));for(const c of sorted){const o=document.createElement('option');o.value=String(c.sqcand);o.textContent=`${c.n} • ${c.nmu||c.n}${c.party?` (${c.party})`:''}`;s.appendChild(o)}sel=cands.find(c=>String(c.sqcand)===prev)||sorted.find(validDest)||sorted[0]||null;if(sel)s.value=String(sel.sqcand);s.disabled=!sel}
function render(stale=false){if(!data||!sel)return;const m=met(data,sel),sp=pct(data?.s?.pstn??data?.s?.pst),ts=num(data?.s?.ts),st=num(data?.s?.st),tv=num(data?.v?.tv),ok=validDest(sel);$('candidateName').textContent=sel.nmu||sel.nm||'Candidato';$('candidateParty').textContent=[sel.party,sel.group].filter(Boolean).join(' • ')||'—';$('candidateShare').textContent=m.vv?`${fp.format(m.share)}%`:'—';$('shareRing').style.setProperty('--share',`${Math.min(360,m.share*3.6)}deg`);$('sectionsPct').textContent=`${fp.format(sp)}%`;$('sectionsCount').textContent=ts?`${fi.format(st)} de ${fi.format(ts)} seções`:'—';$('validVotes').textContent=fi.format(m.vv);$('totalVotes').textContent=tv?`${fi.format(tv)} votos computados no total`:'—';$('candidateVotes').textContent=fi.format(m.cv);$('candidateBallot').textContent=sel.n?`número ${sel.n}`:'—';
if(!m.vv||!ok){$('halfDelta').textContent='—';$('halfDeltaLabel').textContent=ok?'Aguardando votos válidos':'Votos não classificados como válidos'}else if(m.delta>=0){$('halfDelta').textContent=`+${fi.format(m.delta)}`;$('halfDeltaLabel').textContent='votos acima da maioria dos válidos já apurados'}else{$('halfDelta').textContent=fi.format(-m.delta);$('halfDeltaLabel').textContent='votos abaixo da maioria dos válidos já apurados'}
$('remainingElectors').textContent=fi.format(m.rem);$('worstCaseVotes').textContent=m.worst<=m.rem?fi.format(m.worst):'Fora do alcance';$('worstCaseShare').textContent=m.rem&&m.worst<=m.rem?`${fp.format(100*m.worst/m.rem)}% do teto de votos restantes, se todos fossem válidos.`:m.rem?'Mesmo todo o teto de votos restantes não bastaria nesse cenário extremo.':'Não há eleitorado restante em seções não totalizadas.';$('guaranteedStatus').textContent=m.guaranteed?'Sim':'Não';
const b=$('mathState');b.className='state-badge';if(!m.vv){b.textContent='Aguardando';$('mathSummary').textContent='Ainda não há votos válidos suficientes para calcular o envelope matemático.'}else if(m.guaranteed){b.classList.add('guaranteed');b.textContent='Maioria matematicamente garantida';$('mathSummary').textContent='A maioria absoluta permaneceria acima de 50% mesmo no cenário extremo mais desfavorável permitido pelo eleitorado ainda não totalizado.'}else if(m.impossible){b.classList.add('impossible');b.textContent='Maioria matematicamente inalcançável';$('mathSummary').textContent='Mesmo o teto máximo de votos restantes não permitiria ultrapassar 50% dos votos válidos.'}else{b.classList.add('open');b.textContent='Matematicamente em aberto';$('mathSummary').textContent='Há combinações possíveis dos votos restantes que terminam acima de 50% e outras abaixo. O simulador testa cenários sem atribuir probabilidade.'}
const when=[data.dg,data.hg].filter(Boolean).join(' às ');$('lastUpdate').textContent=`Última leitura: ${when||new Date().toLocaleTimeString('pt-BR')}${stale?' • cache local':''}`;scenario()}
function scenario(){if(!data||!sel)return;const m=met(data,sel),vr=num($('validRate').value)/100,cr=num($('candidateRate').value)/100,nv=Math.round(m.rem*vr),nc=Math.round(nv*cr),fv=m.vv+nv,fc=m.cv+nc,s=fv?100*fc/fv:0;$('validRateValue').textContent=`${fp.format(100*vr)}%`;$('candidateRateValue').textContent=`${fp.format(100*cr)}%`;$('scenarioShare').textContent=fv?`${fp.format(s)}%`:'—';$('scenarioNewValid').textContent=fi.format(nv);$('scenarioCandidateVotes').textContent=fi.format(nc);const v=$('scenarioVerdict');v.className='verdict';if(!fv)v.textContent='Sem votos válidos no cenário';else if(fc>fv/2){v.classList.add('above');v.textContent='Neste cenário: acima de 50%'}else{v.classList.add('below');v.textContent='Neste cenário: 50% ou menos'}}
async function refresh(manual=false){if(busy)return;busy=true;if(manual)$('refreshButton').textContent='Atualizando…';try{const r=await load(url('BR'),'tse26-br');data=r.j;cands=candidates(data);if(!cands.length){source('','TSE • aguardando votos');notice('waiting','O arquivo oficial está disponível, mas ainda não trouxe votação. O painel continuará tentando automaticamente.');return}fillSelect();render(r.stale);source(r.stale?'error':'live',r.stale?'TSE • última leitura':'TSE • dados oficiais');notice(r.stale?'error':'live',r.stale?'Exibindo o último dado salvo neste navegador.':'Dados oficiais carregados. Atualização automática a cada 15 segundos.')}catch{source('error','TSE • aguardando fonte');notice('waiting','A divulgação oficial ainda não está acessível nesta leitura. O painel tentará novamente automaticamente.')}finally{busy=false;if(manual)$('refreshButton').textContent='Atualizar agora'}}
async function getUf(u){try{const r=await load(url(u),`tse26-${u}`,6500),list=candidates(r.j),c=list.find(x=>String(x.sqcand)===String(sel?.sqcand))||list.find(x=>String(x.n)===String(sel?.n));if(!c)return{u};const m=met(r.j,c);return{u,ok:true,share:m.share,sec:pct(r.j?.s?.pstn??r.j?.s?.pst)}}catch{return{u}}}
function ufCard(x){const e=document.createElement('article');e.className=`state-card${x.ok?'':' loading'}`;e.innerHTML=`<div class="uf"><strong>${x.u}</strong><span>${UF[x.u]}</span></div><strong class="uf-share">${x.ok?`${fp.format(x.share)}%`:'—'}</strong><small>${x.ok?`${fp.format(x.sec)}% das seções`:'Aguardando dado oficial'}</small>`;return e}
async function refreshUfs(){if(!sel)return;const g=$('statesGrid');if(!g.children.length)CFG.ufs.forEach(u=>g.appendChild(ufCard({u})));const q=[...CFG.ufs],out=[],workers=Array.from({length:6},async()=>{while(q.length)out.push(await getUf(q.shift()))});await Promise.all(workers);g.innerHTML='';out.sort((a,b)=>CFG.ufs.indexOf(a.u)-CFG.ufs.indexOf(b.u)).forEach(x=>g.appendChild(ufCard(x)));$('statesUpdated').textContent=`Atualizado ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`}
$('candidateSelect').addEventListener('change',()=>{sel=cands.find(c=>String(c.sqcand)===$('candidateSelect').value)||sel;render();refreshUfs()});$('refreshButton').addEventListener('click',async()=>{await refresh(true);await refreshUfs()});$('validRate').addEventListener('input',scenario);$('candidateRate').addEventListener('input',scenario);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh()});
(async()=>{await refresh();await refreshUfs();setInterval(refresh,CFG.mainMs);setInterval(refreshUfs,CFG.ufMs)})();
