'use strict';
(A=>{
const {E,esc}=A;
A.addUser=q=>{E('askWelcome')?.remove();const a=document.createElement('article');a.className='ask-message ask-message-user';a.innerHTML=`<div class="ask-avatar user">Você</div><div class="ask-bubble"><p>${esc(q)}</p></div>`;E('askThread').append(a);A.scroll()};
A.shell=()=>{const a=document.createElement('article'),id='a'+Date.now();a.className='ask-message ask-message-assistant';a.innerHTML=`<div class="ask-avatar bot">26</div><div class="ask-bubble" id="${id}"><div class="ask-thinking"><i></i><i></i><i></i></div></div>`;E('askThread').append(a);A.scroll();return E(id)};
A.bind=r=>{r.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{navigateRace(b.dataset.open,b.dataset.uf);A.setExplorer(true)});r.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>A.ask(b.dataset.q))};
A.reply=(r,h,qs=[])=>{r.innerHTML=h+(qs.length?`<div class="ask-followups">${qs.map(q=>`<button data-q="${esc(q)}">${esc(q)}</button>`).join('')}</div>`:'');A.bind(r);A.scroll()};
A.fail=r=>A.reply(r,'<p>Não consegui interpretar essa pergunta com segurança. Informe um cargo, uma UF ou o tipo de dado que quer consultar.</p>',['Quem foi eleito deputado estadual em MG?','Como ficou a composição da Câmara no DF?','Compare brancos e nulos entre DF e GO']);
A.recent=q=>{let a=[];try{a=JSON.parse(localStorage.getItem(A.RK)||'[]')}catch{}a=[q,...a.filter(x=>x!==q)].slice(0,7);localStorage.setItem(A.RK,JSON.stringify(a));A.renderRecent()};
A.renderRecent=()=>{let a=[];try{a=JSON.parse(localStorage.getItem(A.RK)||'[]')}catch{}E('askRecent').innerHTML=a.length?'':'<p class="ask-no-recent">Suas perguntas aparecerão aqui.</p>';for(const q of a){const b=document.createElement('button');b.textContent=q;b.onclick=()=>A.ask(q);E('askRecent').append(b)}};
A.addWelcome=()=>{E('askThread').innerHTML='<section class="ask-welcome" id="askWelcome"><div class="ask-mark">26</div><h1>O que você quer saber<br>sobre as Eleições 2026?</h1><p>Pergunte em linguagem natural. A IA entende a intenção; votos, cadeiras e situações são calculados exclusivamente a partir dos dados oficiais do TSE.</p><div class="ask-suggestions" id="askSuggestions"><button>Quem foi eleito deputado estadual em MG?</button><button>Como ficou a composição da Câmara no DF?</button><button>Compare brancos e nulos entre DF e GO</button><button>Quais estados ainda não terminaram a totalização?</button></div></section>';A.wireSug()};
A.wireSug=()=>document.querySelectorAll('#askSuggestions button').forEach(b=>b.onclick=()=>A.ask(b.textContent));
A.scroll=()=>requestAnimationFrame(()=>{const x=E('askThread');x.scrollTop=x.scrollHeight});
A.ask=async q=>{q=String(q||'').trim();if(!q||A.state.busy)return;A.state.busy=true;E('askInput').disabled=E('askSend').disabled=true;A.addUser(q);A.recent(q);const u=new URL(location.href);u.search='';u.searchParams.set('q',q);history.replaceState({},'',u);const r=A.shell();try{if(A.smartRoute)await A.smartRoute(q,r);else{await A.route(q,r);E('askSourceStatus').textContent='Dados oficiais do TSE'}}catch(e){console.error(e);A.reply(r,'<p>Não consegui consultar a fonte oficial agora. Tente novamente em alguns segundos.</p>');E('askSourceStatus').textContent='Fonte TSE temporariamente indisponível'}finally{A.state.busy=false;E('askInput').disabled=E('askSend').disabled=false;E('askInput').value='';E('askInput').focus()}};
A.newChat=()=>{A.resetAIContext?.();A.addWelcome();history.replaceState({},'',location.pathname);A.refreshAIStatus?.();E('askInput').focus()};
A.resize=()=>{const x=E('askInput');x.style.height='auto';x.style.height=Math.min(150,x.scrollHeight)+'px'};
A.wire=()=>{document.body.classList.add('experience-ready','ask-mode');E('askForm').onsubmit=e=>{e.preventDefault();A.ask(E('askInput').value)};E('askInput').oninput=A.resize;E('askInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();E('askForm').requestSubmit()}};E('askNewChat').onclick=A.newChat;E('askOpenExplorer').onclick=E('askTopExplorer').onclick=()=>A.setExplorer(true);E('experienceBrand')?.addEventListener('click',e=>{e.preventDefault();A.setExplorer(false);A.newChat()});A.renderRecent();A.wireSug();A.refreshAIStatus?.();const q=new URLSearchParams(location.search).get('q');if(q)A.ask(q)};
A.wire();
})(window.E360Ask);
