'use strict';
const CFG={base:'https://resultados.tse.jus.br/oficial/ele2026',pollMs:3000,mapMs:45000,maxBackoffMs:30000,ufs:['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO']};
const UF={AC:'Acre',AL:'Alagoas',AP:'Amapá',AM:'Amazonas',BA:'Bahia',CE:'Ceará',DF:'Distrito Federal',ES:'Espírito Santo',GO:'Goiás',MA:'Maranhão',MT:'Mato Grosso',MS:'Mato Grosso do Sul',MG:'Minas Gerais',PA:'Pará',PB:'Paraíba',PR:'Paraná',PE:'Pernambuco',PI:'Piauí',RJ:'Rio de Janeiro',RN:'Rio Grande do Norte',RS:'Rio Grande do Sul',RO:'Rondônia',RR:'Roraima',SC:'Santa Catarina',SP:'São Paulo',SE:'Sergipe',TO:'Tocantins'};
const POS={RR:[1,3],AP:[1,7],AM:[2,2],PA:[2,6],MA:[2,8],AC:[3,1],RO:[3,3],TO:[3,6],PI:[3,8],CE:[3,9],MT:[4,4],GO:[4,5],BA:[4,7],RN:[4,9],MS:[5,4],DF:[5,5],MG:[5,6],PE:[5,8],PB:[5,9],SP:[6,5],ES:[6,7],AL:[6,8],PR:[7,5],RJ:[7,6],SE:[7,8],RS:[8,4],SC:[8,5]};
const OFFICES={
president:{label:'Presidente',code:'0001',election:'6257',scope:'federal',rule:'Maioria absoluta',majority:true},
governor:{label:'Governador',code:'0003',election:'6259',scope:'state',rule:'Maioria absoluta',majority:true},
senator:{label:'Senador',code:'0005',election:'6259',scope:'state',rule:'2 vagas em 2026',senate:true},
federalDeputy:{label:'Deputado Federal',code:'0006',election:'6259',scope:'state',rule:'Sistema proporcional',proportional:true},
stateDeputy:{label:'Deputado Estadual/Distrital',code:'dynamic',election:'6259',scope:'state',rule:'Sistema proporcional',proportional:true}};
const $=id=>document.getElementById(id),fi=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}),fp=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}),fpp=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:3,maximumFractionDigits:3});
let officeKey='president',scope='BR',data=null,candidates=[],selected=null,busy=false,failures=0,nextAt=0,timer=null,mapTimer=null,countdownTimer=null,lastSuccessAt=0,lastDistinctKey='',mapGeneration=0;
const num=(v,d=0)=>{if(v===null||v===undefined||v==='')return d;if(typeof v==='number')return Number.isFinite(v)?v:d;let s=String(v).trim();if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:d};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),pct=v=>clamp(num(v),0,100),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),signed=(n,f=fi)=>`${n>0?'+':''}${f.format(n)}`;
const office=()=>OFFICES[officeKey],officeCode=(uf=scope)=>officeKey==='stateDeputy'?(uf==='DF'?'0008':'0007'):office().code,officeLabel=(uf=scope)=>officeKey==='stateDeputy'?(uf==='DF'?'Deputado Distrital':'Deputado Estadual'):office().label,scopeLabel=(uf=scope)=>uf==='BR'?'Brasil':`${uf} • ${UF[uf]}`;
function resultUrl(uf=scope){const o=office(),s=uf.toLowerCase(),e=String(o.election).padStart(6,'0'),c=officeCode(uf);return `${CFG.base}/${o.election}/dados/${s}/${s}-c${c}-e${e}-u.json`}
const storageKey=(uf=scope)=>`tse26-v5-${officeKey}-${uf}`,historyKey=()=>`tse26-history-v5-${officeKey}-${scope}`,distinctKey=j=>String(j?.idg||[j?.dg,j?.hg,j?.s?.st,j?.v?.vv].join('|'));
function flattenCandidates(j){const out=[];for(const cargo of j?.carg||[])for(const agr of cargo?.agr||[])for(const par of agr?.par||[])for(const cand of par?.cand||[])out.push({...cand,party:par?.sg||'',partyName:par?.nm||'',group:agr?.nm||'',destination:cand?.dvt||par?.dvt||''});return out}
function candidateShare(c,j){const r=num(c?.pvap,NaN);if(Number.isFinite(r))return r;const vv=num(j?.v?.vv),cv=num(c?.vap);return vv?100*cv/vv:0}
function validDestination(c){const d=String(c?.destination||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return !d||d.startsWith('valido')}
function metrics(j,c){const vv=num(j?.v?.vv),cv=num(c?.vap),share=c?candidateShare(c,j):0,te=num(j?.e?.te),est=num(j?.e?.est),rem=Math.max(0,num(j?.e?.esnt,Math.max(0,te-est)));return{vv,cv,share,rem,sections:pct(j?.s?.pstn??j?.s?.pst),totalSections:num(j?.s?.ts),doneSections:num(j?.s?.st),totalVotes:num(j?.v?.tv)}}
function majorityMath(m){const maxValid=m.vv+m.rem,currentThreshold=Math.floor(m.vv/2)+1,extremeThreshold=Math.floor(maxValid/2)+1;return{minShare:maxValid?100*m.cv/maxValid:0,maxShare:maxValid?100*(m.cv+m.rem)/maxValid:0,diffCurrent:m.cv-currentThreshold,needExtreme:Math.max(0,extremeThreshold-m.cv),remainingShareNeeded:m.rem?100*Math.max(0,extremeThreshold-m.cv)/m.rem:0}}
function genericRange(m){if(office().senate){const minDen=m.vv+2*m.rem,maxDen=m.vv+m.rem;return{min:minDen?100*m.cv/minDen:0,max:maxDen?100*(m.cv+m.rem)/maxDen:0}}const den=m.vv+m.rem;return{min:den?100*m.cv/den:0,max:den?100*(m.cv+m.rem)/den:0}}
async function fetchJson(url,key,timeoutMs=7500){const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),timeoutMs);try{const r=await fetch(url,{cache:'no-cache',headers:{Accept:'application/json'},signal:ctl.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();try{localStorage.setItem(key,JSON.stringify(j))}catch{}return{j,stale:false}}catch(error){try{const cached=localStorage.getItem(key);if(cached)return{j:JSON.parse(cached),stale:true,error}}catch{}throw error}finally{clearTimeout(to)}}
function history(){try{return JSON.parse(localStorage.getItem(historyKey())||'[]')}catch{return[]}}
function saveSnapshot(j){const key=distinctKey(j);if(!key||key===lastDistinctKey)return false;lastDistinctKey=key;const vv=num(j?.v?.vv),sections=pct(j?.s?.pstn??j?.s?.pst),map={};for(const c of flattenCandidates(j))map[String(c.sqcand)]={votes:num(c.vap),share:candidateShare(c,j),number:String(c.n||'')};const h=history();if(h.some(x=>x.key===key))return false;h.push({key,ts:Date.now(),label:[j?.dg,j?.hg].filter(Boolean).join(' '),sections,vv,c:map});while(h.length>180)h.shift();try{localStorage.setItem(historyKey(),JSON.stringify(h))}catch{}return true}
function candidateHistory(){if(!selected)return[];const id=String(selected.sqcand),n=String(selected.n||'');return history().map(x=>{const c=x.c?.[id]||Object.values(x.c||{}).find(v=>String(v.number)===n);return c?{...x,cv:c.votes,share:c.share}:null}).filter(Boolean)}
function source(kind,text){const p=$('sourcePill');p.classList.remove('live','error');if(kind)p.classList.add(kind);$('sourceStatus').textContent=text}
function notice(kind,text){const n=$('notice');n.className=`notice ${kind}`;n.textContent=text}
function chooseSelected(){const prev=selected?.sqcand&&String(selected.sqcand);selected=candidates.find(c=>String(c.sqcand)===prev)||[...candidates].sort((a,b)=>num(a.n)-num(b.n)).find(validDestination)||[...candidates].sort((a,b)=>num(a.n)-num(b.n))[0]||null}
